# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=32)),
                ('user_register_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_head_img', models.CharField(max_length=255)),
                ('user_login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
